export const devicons = {
	C: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg",
	"C++": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg",
	Go: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg",
	Java: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg",
	JavaScript: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg",
	Kotlin:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg",
	Lua: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/lua/lua-original.svg",
	MATLAB:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/matlab/matlab-original.svg",
	"Objective-C":
		"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/objectivec/objectivec-plain.svg",
	Perl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/perl/perl-original.svg",
	Python: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg",
	PHP: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg",
	Rust: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-plain.svg",
	Swift: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg",
	VBA: "https://www.logo.wine/a/logo/Microsoft_Excel/Microsoft_Excel-Logo.wine.svg",
	"C#": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg",
	TypeScript: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
	Ruby: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ruby/ruby-original.svg",
	R: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rstudio/rstudio-original.svg",
};